import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const montserrat = Poppins({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={montserrat.className}>{children}</body>
		</html>
	)
}
